language: node_js
node_js:
  - "6"
  - "5"
  - "4"
services:
  - redis-server
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: npm run test:coverage
after_success: npm run coveralls